config/routes.rb
Sharefev::Application.routes.draw do
  root to: 'books#index'

  resources :books,     only: [:index, :show]
  resources :bookmarks, only: [:index, :show]

  namespace :admin do
    resources :books
    resources :bookmarks
  end

end

app/models/book.rb
# -*- encoding : utf-8 -*-
class Book < ActiveRecord::Base
  attr_accessible :name, :title, :checked_url, :linked_url

  extend FriendlyId
  friendly_id :name

  has_many :book_histories, dependent: :restrict
end

app/models/book_history.rb
# -*- encoding : utf-8 -*-
class BookHistory < ActiveRecord::Base
  attr_accessible :hit_text, :no, :year

  has_many :timelines, dependent: :destroy
  belongs_to :book

  scope :recent, limit(3).order('book_histories.created_at desc')
end

app/models/bookmark.rb
# -*- encoding : utf-8 -*-
class Bookmark < ActiveRecord::Base
  attr_accessible :name, :checked_url, :linked_url

  has_many :timelines, dependent: :destroy
end

app/models/ranking.rb
# -*- encoding : utf-8 -*-
class Ranking < ActiveRecord::Base
  attr_accessible :ip_address

  belongs_to :timeline
end

app/models/timeline.rb
# -*- encoding : utf-8 -*-
class Timeline < ActiveRecord::Base
  attr_accessible :book_history_id, :hit_text

  has_many :rankings, dependent: :destroy
  belongs_to :book_history
  belongs_to :bookmark

  validates :book_history_id, uniqueness: {scope: :bookmark_id}
end

app/controllers/admin/bookmarks_controller.rb
# -*- encoding : utf-8 -*-
class Admin::BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(params[:bookmark])
    if @bookmark.save
      redirect_to [:admin, @bookmark], :notice => "Successfully created bookmark."
    else
      render :action => 'new'
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update_attributes(params[:bookmark])
      redirect_to [:admin, @bookmark], :notice  => "Successfully updated bookmark."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to admin_bookmarks_url, :notice => "Successfully destroyed bookmark."
  end
end

app/controllers/admin/books_controller.rb
# -*- encoding : utf-8 -*-
class Admin::BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to [:admin, @book], :notice => "Successfully created book."
    else
      render :action => 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      redirect_to [:admin, @book], :notice  => "Successfully updated book."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_url, :notice => "Successfully destroyed book."
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
# -*- encoding : utf-8 -*-
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/books_controller.rb
# -*- encoding : utf-8 -*-
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/helpers/admin/bookmarks_helper.rb
# -*- encoding : utf-8 -*-
module Admin::BookmarksHelper
end

app/helpers/admin/books_helper.rb
# -*- encoding : utf-8 -*-
module Admin::BooksHelper
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# -*- encoding : utf-8 -*-
module BookmarksHelper
end

app/helpers/books_helper.rb
# -*- encoding : utf-8 -*-
module BooksHelper
end

app/helpers/error_messages_helper.rb
# -*- encoding : utf-8 -*-
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# -*- encoding : utf-8 -*-
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/admin/bookmarks/_form.html.erb
<%= form_for [:admin, @bookmark] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :checked_url %><br />
    <%= f.text_field :checked_url %>
  </p>
  <p>
    <%= f.label :linked_url %><br />
    <%= f.text_field :linked_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/bookmarks/edit.html.erb
<% title "Edit Admin/Bookmark" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @bookmark] %> |
  <%= link_to "View All", admin_bookmarks_path %>
</p>

app/views/admin/bookmarks/index.html.erb
<% title "Admin/Bookmarks" %>

<table>
  <tr>
    <th>Name</th>
    <th>Checked Url</th>
    <th>Linked Url</th>
  </tr>
  <% for bookmark in @bookmarks %>
    <tr>
      <td><%= bookmark.name %></td>
      <td><%= bookmark.checked_url %></td>
      <td><%= bookmark.linked_url %></td>
      <td><%= link_to "Show", [:admin, bookmark] %></td>
      <td><%= link_to "Edit", edit_admin_bookmark_path(bookmark) %></td>
      <td><%= link_to "Destroy", [:admin, bookmark], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/Bookmark", new_admin_bookmark_path %></p>

app/views/admin/bookmarks/new.html.erb
<% title "New Admin/Bookmark" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_bookmarks_path %></p>

app/views/admin/bookmarks/show.html.erb
<% title "Admin/Bookmark" %>

<p>
  <strong>Name:</strong>
  <%= @bookmark.name %>
</p>
<p>
  <strong>Checked Url:</strong>
  <%= @bookmark.checked_url %>
</p>
<p>
  <strong>Linked Url:</strong>
  <%= @bookmark.linked_url %>
</p>

<p>
  <%= link_to "Edit", edit_admin_bookmark_path(@bookmark) %> |
  <%= link_to "Destroy", [:admin, @bookmark], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_bookmarks_path %>
</p>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :checked_url %><br />
    <%= f.text_field :checked_url %>
  </p>
  <p>
    <%= f.label :linked_url %><br />
    <%= f.text_field :linked_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/books/edit.html.erb
<% title "Edit Admin/Book" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @book] %> |
  <%= link_to "View All", admin_books_path %>
</p>

app/views/admin/books/index.html.erb
<% title "Admin/Books" %>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Checked Url</th>
    <th>Linked Url</th>
  </tr>
  <% for book in @books %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.title %></td>
      <td><%= book.checked_url %></td>
      <td><%= book.linked_url %></td>
      <td><%= link_to "Show", [:admin, book] %></td>
      <td><%= link_to "Edit", edit_admin_book_path(book) %></td>
      <td><%= link_to "Destroy", [:admin, book], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/Book", new_admin_book_path %></p>

app/views/admin/books/new.html.erb
<% title "New Admin/Book" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_books_path %></p>

app/views/admin/books/show.html.erb
<% title "Admin/Book" %>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>Checked Url:</strong>
  <%= @book.checked_url %>
</p>
<p>
  <strong>Linked Url:</strong>
  <%= @book.linked_url %>
</p>

<p>
  <%= link_to "Edit", edit_admin_book_path(@book) %> |
  <%= link_to "Destroy", [:admin, @book], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_books_path %>
</p>

app/views/bookmarks/index.html.erb
<% title "Bookmarks" %>

<table>
  <tr>
    <th>Name</th>
    <th>Checked Url</th>
    <th>Linked Url</th>
  </tr>
  <% for bookmark in @bookmarks %>
    <tr>
      <td><%= bookmark.name %></td>
      <td><%= bookmark.checked_url %></td>
      <td><%= bookmark.linked_url %></td>
      <td><%= link_to "Show", bookmark %></td>
    </tr>
  <% end %>
</table>

app/views/bookmarks/show.html.erb
<% title "Bookmark" %>

<p>
  <strong>Name:</strong>
  <%= @bookmark.name %>
</p>
<p>
  <strong>Checked Url:</strong>
  <%= @bookmark.checked_url %>
</p>
<p>
  <strong>Linked Url:</strong>
  <%= @bookmark.linked_url %>
</p>

<p>
  <%= link_to "View All", bookmarks_path %>
</p>

app/views/books/index.html.erb
<% title "Books" %>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Checked Url</th>
    <th>Linked Url</th>
  </tr>
  <% for book in @books %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.title %></td>
      <td><%= book.checked_url %></td>
      <td><%= book.linked_url %></td>
      <td><%= link_to "Show", book %></td>
    </tr>
  <% end %>
</table>

app/views/books/show.html.erb
<% title "Book" %>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>Checked Url:</strong>
  <%= @book.checked_url %>
</p>
<p>
  <strong>Linked Url:</strong>
  <%= @book.linked_url %>
</p>

<p>
  <%= link_to "View All", books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>